add_test([=[TestAlgorithm.SelectionSort]=]  C:/Users/gmude/Development/BasicCppLibrary/BasicCppLibrary/Debug/LibTest.exe [==[--gtest_filter=TestAlgorithm.SelectionSort]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TestAlgorithm.SelectionSort]=]  PROPERTIES WORKING_DIRECTORY C:/Users/gmude/Development/BasicCppLibrary/BasicCppLibrary SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TestAlgorithm.BubbleSort]=]  C:/Users/gmude/Development/BasicCppLibrary/BasicCppLibrary/Debug/LibTest.exe [==[--gtest_filter=TestAlgorithm.BubbleSort]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TestAlgorithm.BubbleSort]=]  PROPERTIES WORKING_DIRECTORY C:/Users/gmude/Development/BasicCppLibrary/BasicCppLibrary SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TestAlgorithm.MergeSort]=]  C:/Users/gmude/Development/BasicCppLibrary/BasicCppLibrary/Debug/LibTest.exe [==[--gtest_filter=TestAlgorithm.MergeSort]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TestAlgorithm.MergeSort]=]  PROPERTIES WORKING_DIRECTORY C:/Users/gmude/Development/BasicCppLibrary/BasicCppLibrary SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TestAlgorithm.QuickSort]=]  C:/Users/gmude/Development/BasicCppLibrary/BasicCppLibrary/Debug/LibTest.exe [==[--gtest_filter=TestAlgorithm.QuickSort]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TestAlgorithm.QuickSort]=]  PROPERTIES WORKING_DIRECTORY C:/Users/gmude/Development/BasicCppLibrary/BasicCppLibrary SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TestAlgorithm.BitRadixSort]=]  C:/Users/gmude/Development/BasicCppLibrary/BasicCppLibrary/Debug/LibTest.exe [==[--gtest_filter=TestAlgorithm.BitRadixSort]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TestAlgorithm.BitRadixSort]=]  PROPERTIES WORKING_DIRECTORY C:/Users/gmude/Development/BasicCppLibrary/BasicCppLibrary SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TestAlgorithm.BinarySearch]=]  C:/Users/gmude/Development/BasicCppLibrary/BasicCppLibrary/Debug/LibTest.exe [==[--gtest_filter=TestAlgorithm.BinarySearch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TestAlgorithm.BinarySearch]=]  PROPERTIES WORKING_DIRECTORY C:/Users/gmude/Development/BasicCppLibrary/BasicCppLibrary SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  LibTest_TESTS TestAlgorithm.SelectionSort TestAlgorithm.BubbleSort TestAlgorithm.MergeSort TestAlgorithm.QuickSort TestAlgorithm.BitRadixSort TestAlgorithm.BinarySearch)
